BOT_PROTOCOL = 'http'
BOT_HOST = '0.0.0.0'
BOT_PORT = 5005
BOT_PING_PATH = '/'
BOT_CHAT_PATH = '/webhooks/rest/webhook'
BOT_BASE_URL = f"{BOT_PROTOCOL}://{BOT_HOST}:{BOT_PORT}"
BOT_PING_URL = f"{BOT_BASE_URL}{BOT_PING_PATH}"
BOT_CHAT_URL = f"{BOT_BASE_URL}{BOT_CHAT_PATH}"
